import { GitWrappedData } from "@/types/wrapped";

/**
 * Balanced Full-Stack Developer Fixture
 * Represents an active software engineer working consistently across frontend and backend.
 */
export const mockBalancedDeveloper: GitWrappedData = {
  user: {
    login: "alexrivera",
    name: "Alex Rivera",
    avatarUrl: "https://avatars.githubusercontent.com/u/583231?v=4",
    bio: "Full-stack engineer building delightful developer tools & open-source software.",
    company: "@techcraft",
    location: "San Francisco, CA",
    websiteUrl: "https://alexrivera.dev",
    twitterUsername: "alexrivera_dev",
    publicRepos: 38,
    followers: 412,
    following: 189,
    createdAt: "2019-03-15T10:20:30Z",
  },
  metrics: {
    year: 2026,
    totalContributions: 1482,
    totalCommits: 1140,
    totalPullRequests: 194,
    totalIssues: 68,
    totalReviews: 80,
    restrictedContributionsCount: 0,
    longestStreakDays: 34,
    currentStreakDays: 12,
    busiestDay: {
      date: "2026-06-18",
      count: 23,
    },
  },
  languages: {
    ownedLanguages: [
      { name: "TypeScript", color: "#3178c6", bytes: 1420000, percentage: 52.4 },
      { name: "Python", color: "#3572A5", bytes: 640000, percentage: 23.6 },
      { name: "Go", color: "#00ADD8", bytes: 390000, percentage: 14.4 },
      { name: "CSS", color: "#563d7c", bytes: 160000, percentage: 5.9 },
      { name: "Rust", color: "#dea584", bytes: 100000, percentage: 3.7 },
    ],
    topLanguage: {
      name: "TypeScript",
      color: "#3178c6",
      bytes: 1420000,
      percentage: 52.4,
    },
    totalBytes: 2710000,
    totalUniqueLanguages: 5,
  },
  circadian: {
    days: [
      { day: "Monday", shortDay: "Mon", isoWeekday: 1, count: 260, percentage: 17.5 },
      { day: "Tuesday", shortDay: "Tue", isoWeekday: 2, count: 320, percentage: 21.6 },
      { day: "Wednesday", shortDay: "Wed", isoWeekday: 3, count: 345, percentage: 23.3 },
      { day: "Thursday", shortDay: "Thu", isoWeekday: 4, count: 285, percentage: 19.2 },
      { day: "Friday", shortDay: "Fri", isoWeekday: 5, count: 182, percentage: 12.3 },
      { day: "Saturday", shortDay: "Sat", isoWeekday: 6, count: 52, percentage: 3.5 },
      { day: "Sunday", shortDay: "Sun", isoWeekday: 7, count: 38, percentage: 2.6 },
    ],
    peakDay: "Wednesday",
    peakDayCount: 345,
    weekendPercentage: 6.1,
    weekdayPercentage: 93.9,
    patternType: "midweek_sprinter",
    patternLabel: "Midweek Sprinter",
    timezoneNote: "Calculated from GitHub contribution calendar (UTC/profile timezone)",
  },
  repositories: {
    mostStarred: {
      name: "hyper-cache",
      nameWithOwner: "alexrivera/hyper-cache",
      description: "Ultra-fast distributed in-memory cache for TypeScript services",
      stars: 485,
      forks: 42,
      primaryLanguage: { name: "TypeScript", color: "#3178c6" },
      url: "https://github.com/alexrivera/hyper-cache",
      isFork: false,
      commitsInYear: 320,
    },
    mostActive: {
      name: "dev-orchestrator",
      nameWithOwner: "alexrivera/dev-orchestrator",
      description: "Local development environment orchestrator with instant reload",
      stars: 182,
      forks: 18,
      primaryLanguage: { name: "Go", color: "#00ADD8" },
      url: "https://github.com/alexrivera/dev-orchestrator",
      isFork: false,
      commitsInYear: 412,
    },
    topOwned: [
      {
        name: "hyper-cache",
        nameWithOwner: "alexrivera/hyper-cache",
        description: "Ultra-fast distributed in-memory cache for TypeScript services",
        stars: 485,
        forks: 42,
        primaryLanguage: { name: "TypeScript", color: "#3178c6" },
        url: "https://github.com/alexrivera/hyper-cache",
        isFork: false,
      },
      {
        name: "dev-orchestrator",
        nameWithOwner: "alexrivera/dev-orchestrator",
        description: "Local development environment orchestrator with instant reload",
        stars: 182,
        forks: 18,
        primaryLanguage: { name: "Go", color: "#00ADD8" },
        url: "https://github.com/alexrivera/dev-orchestrator",
        isFork: false,
      },
      {
        name: "dotfiles-2026",
        nameWithOwner: "alexrivera/dotfiles-2026",
        description: "My personal macOS & Linux dotfiles and shell setup",
        stars: 34,
        forks: 6,
        primaryLanguage: { name: "Shell", color: "#89e051" },
        url: "https://github.com/alexrivera/dotfiles-2026",
        isFork: false,
      },
    ],
  },
  persona: {
    archetype: "full_stack_alchemist",
    eraTitle: "The Full-Stack Alchemist",
    badge: "🔮 Master of All Layers",
    roast: "You have 14 tabs open about microservices when your app only has 12 active users.",
    praise: "Consistently shipped across the entire stack, balancing backend stability with clean frontend interfaces.",
    superpower: "Writing TypeScript that compiles on the very first try.",
    kryptonite: "Resolving merge conflicts in package-lock.json.",
    spiritTool: "pnpm & docker-compose",
  },
  year: 2026,
  generatedAt: "2026-09-25T12:00:00.000Z",
  isMock: true,
};

/**
 * Weekend Warrior Fixture
 * Represents an open-source contributor or hobbyist who hacks primarily on weekends.
 */
export const mockWeekendWarrior: GitWrappedData = {
  user: {
    login: "maya-codes",
    name: "Maya Chen",
    avatarUrl: "https://avatars.githubusercontent.com/u/9919?v=4",
    bio: "Systems programmer by night, open-source enthusiast on weekends. Rust & WebAssembly.",
    company: null,
    location: "Berlin, Germany",
    websiteUrl: "https://mayachen.rs",
    twitterUsername: "mayacodes_rs",
    publicRepos: 22,
    followers: 670,
    following: 95,
    createdAt: "2018-06-11T14:40:00Z",
  },
  metrics: {
    year: 2026,
    totalContributions: 890,
    totalCommits: 710,
    totalPullRequests: 110,
    totalIssues: 42,
    totalReviews: 28,
    restrictedContributionsCount: 0,
    longestStreakDays: 14,
    currentStreakDays: 2,
    busiestDay: {
      date: "2026-04-12",
      count: 36,
    },
  },
  languages: {
    ownedLanguages: [
      { name: "Rust", color: "#dea584", bytes: 1850000, percentage: 68.2 },
      { name: "C++", color: "#f34b7d", bytes: 520000, percentage: 19.2 },
      { name: "Python", color: "#3572A5", bytes: 210000, percentage: 7.7 },
      { name: "WebAssembly", color: "#04133b", bytes: 130000, percentage: 4.9 },
    ],
    topLanguage: {
      name: "Rust",
      color: "#dea584",
      bytes: 1850000,
      percentage: 68.2,
    },
    totalBytes: 2710000,
    totalUniqueLanguages: 4,
  },
  circadian: {
    days: [
      { day: "Monday", shortDay: "Mon", isoWeekday: 1, count: 65, percentage: 7.3 },
      { day: "Tuesday", shortDay: "Tue", isoWeekday: 2, count: 70, percentage: 7.9 },
      { day: "Wednesday", shortDay: "Wed", isoWeekday: 3, count: 85, percentage: 9.6 },
      { day: "Thursday", shortDay: "Thu", isoWeekday: 4, count: 90, percentage: 10.1 },
      { day: "Friday", shortDay: "Fri", isoWeekday: 5, count: 120, percentage: 13.5 },
      { day: "Saturday", shortDay: "Sat", isoWeekday: 6, count: 245, percentage: 27.5 },
      { day: "Sunday", shortDay: "Sun", isoWeekday: 7, count: 215, percentage: 24.1 },
    ],
    peakDay: "Saturday",
    peakDayCount: 245,
    weekendPercentage: 51.6,
    weekdayPercentage: 48.4,
    patternType: "weekend_warrior",
    patternLabel: "Weekend Warrior",
    timezoneNote: "Calculated from GitHub contribution calendar (UTC/profile timezone)",
  },
  repositories: {
    mostStarred: {
      name: "rusty-synth",
      nameWithOwner: "maya-codes/rusty-synth",
      description: "Zero-latency software synthesizer written in Rust and compiled to WebAssembly",
      stars: 1240,
      forks: 98,
      primaryLanguage: { name: "Rust", color: "#dea584" },
      url: "https://github.com/maya-codes/rusty-synth",
      isFork: false,
      commitsInYear: 390,
    },
    mostActive: {
      name: "rusty-synth",
      nameWithOwner: "maya-codes/rusty-synth",
      description: "Zero-latency software synthesizer written in Rust and compiled to WebAssembly",
      stars: 1240,
      forks: 98,
      primaryLanguage: { name: "Rust", color: "#dea584" },
      url: "https://github.com/maya-codes/rusty-synth",
      isFork: false,
      commitsInYear: 390,
    },
    topOwned: [
      {
        name: "rusty-synth",
        nameWithOwner: "maya-codes/rusty-synth",
        description: "Zero-latency software synthesizer written in Rust and compiled to WebAssembly",
        stars: 1240,
        forks: 98,
        primaryLanguage: { name: "Rust", color: "#dea584" },
        url: "https://github.com/maya-codes/rusty-synth",
        isFork: false,
      },
      {
        name: "wasm-audio-driver",
        nameWithOwner: "maya-codes/wasm-audio-driver",
        description: "Low-overhead audio buffer bridge for WebAudio Worklets",
        stars: 310,
        forks: 24,
        primaryLanguage: { name: "C++", color: "#f34b7d" },
        url: "https://github.com/maya-codes/wasm-audio-driver",
        isFork: false,
      },
    ],
  },
  persona: {
    archetype: "weekend_warrior",
    eraTitle: "The Weekend Warrior",
    badge: "⚔️ Saturday Hackathon Champion",
    roast: "While normal people went outside, you spent your entire Sunday fighting the borrow checker.",
    praise: "Dedicated your precious weekends to craft open-source tools with stellar performance.",
    superpower: "Refactoring 2,000 lines of unsafe code on Saturday morning.",
    kryptonite: "Unhelpful compile error E0597.",
    spiritTool: "cargo clippy --fix",
  },
  year: 2026,
  generatedAt: "2026-09-25T12:00:00.000Z",
  isMock: true,
};

/**
 * Specialist Developer Fixture
 * Represents a focused specialist with deep expertise in a single language/domain (Python/AI).
 */
export const mockSpecialistDeveloper: GitWrappedData = {
  user: {
    login: "dr-tensor",
    name: "Dr. Elena Rostova",
    avatarUrl: "https://avatars.githubusercontent.com/u/1024025?v=4",
    bio: "Machine Learning Researcher. Optimizing diffusion models & transformer architectures.",
    company: "Autonomous AI Lab",
    location: "Zurich, Switzerland",
    websiteUrl: "https://rostova.ai",
    twitterUsername: "elena_tensor",
    publicRepos: 15,
    followers: 1820,
    following: 64,
    createdAt: "2017-09-01T08:15:00Z",
  },
  metrics: {
    year: 2026,
    totalContributions: 2150,
    totalCommits: 1820,
    totalPullRequests: 180,
    totalIssues: 90,
    totalReviews: 60,
    restrictedContributionsCount: 0,
    longestStreakDays: 62,
    currentStreakDays: 28,
    busiestDay: {
      date: "2026-02-14",
      count: 48,
    },
  },
  languages: {
    ownedLanguages: [
      { name: "Python", color: "#3572A5", bytes: 4200000, percentage: 89.4 },
      { name: "Cuda", color: "#3A4E58", bytes: 310000, percentage: 6.6 },
      { name: "Shell", color: "#89e051", bytes: 190000, percentage: 4.0 },
    ],
    topLanguage: {
      name: "Python",
      color: "#3572A5",
      bytes: 4200000,
      percentage: 89.4,
    },
    totalBytes: 4700000,
    totalUniqueLanguages: 3,
  },
  circadian: {
    days: [
      { day: "Monday", shortDay: "Mon", isoWeekday: 1, count: 410, percentage: 19.1 },
      { day: "Tuesday", shortDay: "Tue", isoWeekday: 2, count: 480, percentage: 22.3 },
      { day: "Wednesday", shortDay: "Wed", isoWeekday: 3, count: 450, percentage: 20.9 },
      { day: "Thursday", shortDay: "Thu", isoWeekday: 4, count: 390, percentage: 18.1 },
      { day: "Friday", shortDay: "Fri", isoWeekday: 5, count: 320, percentage: 14.9 },
      { day: "Saturday", shortDay: "Sat", isoWeekday: 6, count: 60, percentage: 2.8 },
      { day: "Sunday", shortDay: "Sun", isoWeekday: 7, count: 40, percentage: 1.9 },
    ],
    peakDay: "Tuesday",
    peakDayCount: 480,
    weekendPercentage: 4.7,
    weekdayPercentage: 95.3,
    patternType: "midweek_sprinter",
    patternLabel: "Midweek Sprinter",
    timezoneNote: "Calculated from GitHub contribution calendar (UTC/profile timezone)",
  },
  repositories: {
    mostStarred: {
      name: "fast-latent-diffusion",
      nameWithOwner: "dr-tensor/fast-latent-diffusion",
      description: "Real-time diffusion pipeline with custom FP8 CUDA kernels",
      stars: 3450,
      forks: 310,
      primaryLanguage: { name: "Python", color: "#3572A5" },
      url: "https://github.com/dr-tensor/fast-latent-diffusion",
      isFork: false,
      commitsInYear: 820,
    },
    mostActive: {
      name: "fast-latent-diffusion",
      nameWithOwner: "dr-tensor/fast-latent-diffusion",
      description: "Real-time diffusion pipeline with custom FP8 CUDA kernels",
      stars: 3450,
      forks: 310,
      primaryLanguage: { name: "Python", color: "#3572A5" },
      url: "https://github.com/dr-tensor/fast-latent-diffusion",
      isFork: false,
      commitsInYear: 820,
    },
    topOwned: [
      {
        name: "fast-latent-diffusion",
        nameWithOwner: "dr-tensor/fast-latent-diffusion",
        description: "Real-time diffusion pipeline with custom FP8 CUDA kernels",
        stars: 3450,
        forks: 310,
        primaryLanguage: { name: "Python", color: "#3572A5" },
        url: "https://github.com/dr-tensor/fast-latent-diffusion",
        isFork: false,
      },
      {
        name: "tensor-profiler",
        nameWithOwner: "dr-tensor/tensor-profiler",
        description: "Zero-overhead PyTorch tensor allocation profiler",
        stars: 780,
        forks: 54,
        primaryLanguage: { name: "Python", color: "#3572A5" },
        url: "https://github.com/dr-tensor/tensor-profiler",
        isFork: false,
      },
    ],
  },
  persona: {
    archetype: "specialist_purist",
    eraTitle: "The Python Craftsman",
    badge: "🐍 Pythonic Purist",
    roast: "If a problem cannot be solved with an f-string and a NumPy array, you pretend it does not exist.",
    praise: "Pushed the boundaries of computational science with hyper-optimized Python and CUDA architectures.",
    superpower: "Finding GPU memory leaks before they OOM the cluster.",
    kryptonite: "Working with untyped JavaScript codebases.",
    spiritTool: "uv & PyTorch",
  },
  year: 2026,
  generatedAt: "2026-09-25T12:00:00.000Z",
  isMock: true,
};

/**
 * Inactive / Stealth Lurker Fixture
 * Represents an edge-case user with zero or minimal contributions.
 * Humorous, reassuring, and guarantees zero UI breakages.
 */
export const mockInactiveDeveloper: GitWrappedData = {
  user: {
    login: "zen-coder",
    name: "Jordan Lee",
    avatarUrl: "https://avatars.githubusercontent.com/u/101010?v=4",
    bio: "Living in the moment. Observing code from a respectful distance.",
    company: null,
    location: "Offline",
    websiteUrl: null,
    twitterUsername: null,
    publicRepos: 4,
    followers: 24,
    following: 110,
    createdAt: "2021-01-10T12:00:00Z",
  },
  metrics: {
    year: 2026,
    totalContributions: 6,
    totalCommits: 4,
    totalPullRequests: 1,
    totalIssues: 1,
    totalReviews: 0,
    restrictedContributionsCount: 0,
    longestStreakDays: 2,
    currentStreakDays: 0,
    busiestDay: {
      date: "2026-03-02",
      count: 3,
    },
  },
  languages: {
    ownedLanguages: [
      { name: "Markdown", color: "#083fa1", bytes: 42000, percentage: 65.6 },
      { name: "HTML", color: "#e34c26", bytes: 22000, percentage: 34.4 },
    ],
    topLanguage: {
      name: "Markdown",
      color: "#083fa1",
      bytes: 42000,
      percentage: 65.6,
    },
    totalBytes: 64000,
    totalUniqueLanguages: 2,
  },
  circadian: {
    days: [
      { day: "Monday", shortDay: "Mon", isoWeekday: 1, count: 3, percentage: 50.0 },
      { day: "Tuesday", shortDay: "Tue", isoWeekday: 2, count: 1, percentage: 16.7 },
      { day: "Wednesday", shortDay: "Wed", isoWeekday: 3, count: 1, percentage: 16.7 },
      { day: "Thursday", shortDay: "Thu", isoWeekday: 4, count: 1, percentage: 16.7 },
      { day: "Friday", shortDay: "Fri", isoWeekday: 5, count: 0, percentage: 0.0 },
      { day: "Saturday", shortDay: "Sat", isoWeekday: 6, count: 0, percentage: 0.0 },
      { day: "Sunday", shortDay: "Sun", isoWeekday: 7, count: 0, percentage: 0.0 },
    ],
    peakDay: "Monday",
    peakDayCount: 3,
    weekendPercentage: 0.0,
    weekdayPercentage: 100.0,
    patternType: "zen_sleeper",
    patternLabel: "Zen Sleeper",
    timezoneNote: "Calculated from GitHub contribution calendar (UTC/profile timezone)",
  },
  repositories: {
    mostStarred: {
      name: "reading-list",
      nameWithOwner: "zen-coder/reading-list",
      description: "Curated collection of engineering papers I intend to read eventually",
      stars: 12,
      forks: 1,
      primaryLanguage: { name: "Markdown", color: "#083fa1" },
      url: "https://github.com/zen-coder/reading-list",
      isFork: false,
      commitsInYear: 3,
    },
    mostActive: {
      name: "reading-list",
      nameWithOwner: "zen-coder/reading-list",
      description: "Curated collection of engineering papers I intend to read eventually",
      stars: 12,
      forks: 1,
      primaryLanguage: { name: "Markdown", color: "#083fa1" },
      url: "https://github.com/zen-coder/reading-list",
      isFork: false,
      commitsInYear: 3,
    },
    topOwned: [
      {
        name: "reading-list",
        nameWithOwner: "zen-coder/reading-list",
        description: "Curated collection of engineering papers I intend to read eventually",
        stars: 12,
        forks: 1,
        primaryLanguage: { name: "Markdown", color: "#083fa1" },
        url: "https://github.com/zen-coder/reading-list",
        isFork: false,
      },
    ],
  },
  persona: {
    archetype: "zen_lurker",
    eraTitle: "The Stealth Lurker",
    badge: "🧘 Digital Minimalist",
    roast: "You starred 45 repos this year and contributed to none of them. Peak observational engineering.",
    praise: "Achieved the legendary work-life balance that the rest of us can only dream about.",
    superpower: "Avoiding production outages by committing absolutely nothing.",
    kryptonite: "Unplanned git push notifications.",
    spiritTool: "Do Not Disturb Mode",
  },
  year: 2026,
  generatedAt: "2026-09-25T12:00:00.000Z",
  isMock: true,
};

/**
 * Registry of available mock profiles
 */
export const mockProfiles: Record<string, GitWrappedData> = {
  balanced: mockBalancedDeveloper,
  weekend: mockWeekendWarrior,
  specialist: mockSpecialistDeveloper,
  inactive: mockInactiveDeveloper,
};

/**
 * Returns a mock profile by key, falling back to 'balanced'
 */
export function getMockWrappedData(profileKey: string = "balanced"): GitWrappedData {
  const normalizedKey = profileKey.toLowerCase().trim();
  return mockProfiles[normalizedKey] || mockBalancedDeveloper;
}
